# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'LearnSDWebImage' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LearnSDWebImage

  target 'LearnSDWebImageTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LearnSDWebImageUITests' do
    inherit! :search_paths
    # Pods for testing
  end
  pod 'AFNetworking'
  pod 'SDWebImage'
  pod 'CHTCollectionViewWaterfallLayout/ObjC', '~> 0.9.3'
end
